empresa_direccion_empresa:
    resource: "@EmpresaBundle/Resources/config/routing/direccion_empresa.yml"
    prefix:   /direccion_empresa

empresa_empresa:
    resource: "@EmpresaBundle/Resources/config/routing/empresa.yml"
    prefix:   /empresa

empresa_homepage:
    path:     /hello/{name}
    defaults: { _controller: EmpresaBundle:Default:index }
