DsCorp\Equipo\EquipoBundle\Entity\capacidad:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        capacidad:
            type: string
            length: '10'
    oneToMany:
        caracteristicas_equipo:
            targetEntity: DsCorp\Equipo\EquipoBundle\Entity\caracteristicas_equipo
            mappedBy: capacidad
    lifecycleCallbacks: {  }
