DsCorp\Equipo\EquipoBundle\Entity\procesador:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        marca:
            type: string
            length: '30'
        modelo:
            type: string
            length: '15'
        velocidad:
            type: string
            length: '10'
    oneToMany:
        caracteristicas_equipo:
            targetEntity: DsCorp\Equipo\EquipoBundle\Entity\caracteristicas_equipo
            mappedBy: procesador
    lifecycleCallbacks: {  }
